version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: "@google-cloud/storage"
    versions:
    - 5.7.0
    - 5.7.3
  - dependency-name: mocha
    versions:
    - 8.2.1
