env:
  mocha: true

plugins:
  - 'mocha'

rules:
  'mocha/handle-done-callback': 'error'
  'mocha/no-global-tests': 'error'
  'mocha/no-mocha-arrows': 'error'

  # Prefer arrow functions over function keyword.
  # const foo = (arg1, arg2) => {
  #     stuff(arg1);
  # };
  # const factorial = (value) => {
  #   return value == 0 ? 1 : value * factorial(value - 1);
  # };
  # This rule doesn't enforce it everywhere, but it's a start.
  # It needs an exception to work with Mocha though.
  prefer-arrow-callback: 'off'
