version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Prepare credentials
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS_JSON > /home/circleci/project/credentials.json

      - run:
          name: Run tests
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /home/circleci/project/credentials.json
          command: npm run test:js

      - run:
          name: Check lint
          command: npm run lint
          when: always

      - run:
          name: Check prettier
          command: npm run prettier:check
          when: always
